package com.xm.crud.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tnl_dept.dept_id
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tnl_dept.dept_name
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tnl_dept.dept_id
     *
     * @return the value of tnl_dept.dept_id
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tnl_dept.dept_id
     *
     * @param deptId the value for tnl_dept.dept_id
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tnl_dept.dept_name
     *
     * @return the value of tnl_dept.dept_name
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tnl_dept.dept_name
     *
     * @param deptName the value for tnl_dept.dept_name
     *
     * @mbg.generated Fri May 22 13:57:26 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

	public Department(Integer deptId, String deptName) {
		super();
		this.deptId = deptId;
		this.deptName = deptName;
	}

	public Department() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}